### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by goodandrewsoft** [guyingbo/shadowproxy#2]
After installing shadowproxy i have next errors:

> Traceback (most recent call last):
  File "f:\run\lprogr\phyton\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\run\lprogr\phyton\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Run\Lprogr\Phyton\Scripts\shadowproxy.exe\__main__.py", line 5, in <module>
  File "f:\run\lprogr\phyton\lib\site-packages\shadowproxy\__main__.py", line 7, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

`Python 3.7.3 , Windows 10 x64`

> λ pip freeze            
asyncio==3.4.3          
attrs==19.1.0           
certifi==2019.3.9       
chardet==3.0.4          
curio==0.9              
dukpy==0.2.2            
httptools==0.0.13       
idna==2.8               
iofree==0.1.2           
JsonForm==0.0.2         
jsonschema==3.0.1       
JsonSir==0.0.2          
pproxy==2.1.8           
pycryptodome==3.8.1     
pylru==1.2.0            
pypac==0.12.0           
pyrsistent==0.15.2      
Python-EasyConfig==0.1.7
PyYAML==5.1             
requests==2.21.0        
Resource==0.2.1         
shadowproxy==0.6.5      
six==1.12.0             
tld==0.9.3              
urllib3==1.24.3

**Comment by guyingbo** [comment]
Shadowproxy can not support windows due to its dependency of curio which does not support windows yet. It also use [resource](https://docs.python.org/3/library/resource.html) module which is a Unix specific service.
